name: Build
on:
  workflow_dispatch:
    inputs:
      onnxruntime-version:
        type: string
        description: "ONNX Runtime version (e.g. 1.18.0)"
        required: true
env:
  GCC_VERSION: '11'
  CMAKE_VERSION: '3.28'
  PYTHON_VERSION: '3.10'
  NODE_VERSION: '18'
  XCODE_VERSION: '14.3'
  MACOSX_DEPLOYMENT_TARGET: '10.15'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            cuda: true
            runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.15
        if: matrix.cuda && runner.os != 'macOS'
        with:
          cuda: '12.3.0'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43
      - name: Run builder
        run:
          deno run -A src/build.ts -v ${{ inputs.onnxruntime-version }} -c
